namespace ShellN;

[Flags]
public enum STORAGEITEM_CREATION_FLAGS : uint
{
    SICF_DEFAULT = 0x0,
    SICF_DELETE_NOT_ALLOWED_IF_CONTAINER = 0x1,
    SICF_ALLOW_NAMESPACE_JUNCTION = 0x2,
    SICF_ADVANCED_SHAPES_ALLOWED = 0x4,
    SICF_FILTER_ON_MANIFESTED_TYPES = 0x8,
    SICF_FILTER_ON_MANIFESTED_KINDS = 0x10,
    SICF_DONT_CHECK_PATH_FOR_EXISTENCE = 0x20,
    SICF_FORCE_READ_ONLY = 0x40,
    SICF_INHERITS_LOWIL = 0x80,
    SICF_DISABLE_AQS = 0x100,
    SICF_DISABLE_DEEPQUERY = 0x200,
    SICF_NEIGHBORING_FILES_QUERY = 0x400,
    SICF_DEFAULT_ORDER_BY_DATE = 0x800,
    SICF_NO_FOLDER_CREATE = 0x1000,
    SICF_VALIDATED_ACCESS = 0x2000,
    SICF_CONTENT_INDEXER = 0x4000,
    SICF_ENABLE_FOLDER_REPARSE_TAGS = 0x8000,
    SICF_OR_FILTER_OVER_MANIFESTED_INFO = 0x10000,
    SICF_ALLOW_FULL_NAMESPACE = 0x20000,
    SICF_ALLOW_LINKS = 0x40000,
    SICF_ALLOW_NON_STREAM_FILES = 0x80000,
    SICF_FOLDERID_CAPABILITY_BACKED = 0x100000,
    SICF_BROADFS_CAPABILITY_BACKED = 0x200000,
    SICF_INHERITED_FLAGS_MASK = 0x3F60DC,
}
