namespace ShellBat;

public partial class ShellBatTheme : JsonBasedSettings<ShellBatTheme>
{
    public const string ThemesDirectoryName = "Themes";
    public const string DefaultThemeName = "Default";
    public static string DefaultThemeFilePath => Path.Combine(Settings.ThemesPath, $"{DefaultThemeName}{FileExtension.ShellBatThemeExtensionName}");

    public string ThemeName => FilePath != null ? Path.GetFileNameWithoutExtension(FilePath) : DefaultThemeName;
    public string? DisplayName { get; private set; }
    public virtual string? CssFileName { get; set; }
    public virtual bool IsTopmost { get; set; }
    public virtual float Opacity { get; set; } = 1;
    public virtual string? AcrylicTintColor { get; set; }
    public virtual float AcrylicTintOpacity { get; set; } = 0.2f;
    public virtual float? AcrylicTintLuminosityOpacity { get; set; }

    [JsonIgnore]
    public override string? FilePath { get; set; } = DefaultThemeFilePath;

    // these properties must follow what's found in Variables.css (kebab-case will be automatically generated by JSON serializer)
    public virtual string MainBackgroundColor { get; set; } = "#101010"; // set to "Transparent" to enable transparent behavior (acrylic, etc.)
    public virtual string MainColor { get; set; } = "#F0F0F0";
    public virtual string MainFontFamily { get; set; } = "\"Lucida Console\"";
    public virtual string MainFontSize { get; set; } = "14px";
    public virtual string MainBorderRadius { get; set; } = "4px";
    public virtual string MainPadding { get; set; } = "8px";

    public virtual string BorderColor { get; set; } = "#FFFFFF";
    public virtual string HiddenColor { get; set; } = "#707070";
    public virtual string SystemColor { get; set; } = "#A0A0A0";
    public virtual string EditorFontColor { get; set; } = "#8FFFA2";
    public virtual string EditorBackgroundColor { get; set; } = "#000000";
    public virtual string DisabledColor { get; set; } = "#404040";
    public virtual string HoverColor { get; set; } = "#453001";
    public virtual string SelectedColor { get; set; } = "#665840";

    public virtual string ActionBackgroundColor { get; set; } = "#202020";
    public virtual string ActionFontSize { get; set; } = "16px";
    public virtual string ActionFontFamily { get; set; } = "\"Segoe UI\"";
    public virtual string InputBackgroundColor { get; set; } = "#B8860B";

    public virtual string EntriesFontSize { get; set; } = "1em";
    public virtual string EntriesLineHeight { get; set; } = "0.6em";

    public virtual string MenuItemVerticalPadding { get; set; } = "4px";

    public virtual string PropertyGridFontSize { get; set; } = "14px";
    public virtual string PropertyGridFontFamily { get; set; } = "\"Segoe UI\"";
    public virtual string PropertyGridBackgroundColor { get; set; } = "#FFBF4B";
    public virtual string PropertyGridHeaderBackgroundColor { get; set; } = "#5D5D5D";

    public virtual string ToolbarBackgroundImage { get; set; } = "linear-gradient(to right, var(--main-background-color), var(--main-color))";

    // tooltip, etc.
    public virtual string DescriptionBackgroundColor { get; set; } = "#F7E8B9";
    public virtual string DescriptionColor { get; set; } = "#36395A";

    public virtual string MarkdownViewerFontFamily { get; set; } = "\"Segoe UI\"";
    public virtual string MarkdownViewerBackgroundColor { get; set; } = "#ffffff";
    public virtual string MarkdownViewerColor { get; set; } = "#000000";

    public virtual string WindowHeaderFontFamily { get; set; } = "\"Segoe UI\"";

    public virtual string ButtonBorderRadius { get; set; } = "2px";

    public override string ToString() => $"{ThemeName} {FilePath}";

    internal string SerializeForWebView()
    {
        var json = JsonSerializer.Serialize(this, JsonSourceKebabGenerationContext.Default.ShellBatTheme);
        var theme = JsonSerializer.Deserialize(json, JsonSourceKebabGenerationContext.Default.ShellBatTheme)!;

        // determine if there's a css file aside the file with the same name as the theme
        // don't allow absolute or relative paths
        var cssFileName = IOUtilities.NameToValidFileName(theme.CssFileName.Nullify() ?? ThemeName + ".css");
        theme.CssFileName = null;
        if (cssFileName != null)
        {
            var cssFilePath = Path.Combine(Path.GetDirectoryName(FilePath)!, cssFileName);
            if (IOUtilities.PathIsFile(cssFilePath))
            {
                theme.CssFileName = cssFilePath;
            }
        }

        return JsonSerializer.Serialize(theme, JsonSourceKebabGenerationContext.Default.ShellBatTheme);
    }

    public virtual void SerializeTo(string filePath) => Serialize(JsonSourceKebabGenerationContext.Default);
    public virtual void SerializeTo(Stream stream) => Serialize(stream, JsonSourceKebabGenerationContext.Default);
    public static ShellBatTheme? Deserialize(Stream stream) => Deserialize(stream, JsonSourceKebabGenerationContext.Default, true);
    public static ShellBatTheme? Deserialize(string filePath)
    {
        ArgumentNullException.ThrowIfNull(filePath);
        var theme = Deserialize(filePath, JsonSourceKebabGenerationContext.Default, true);
        theme?.FilePath = filePath;
        return theme;
    }

    public static IReadOnlyList<ShellBatTheme> AvailableThemes
    {
        get
        {
            var list = new List<ShellBatTheme>();
            foreach (var path in GetThemePaths())
            {
                if (!IOUtilities.PathIsDirectory(path))
                    continue;

                var files = Directory.EnumerateFiles(path, $"*{FileExtension.ShellBatThemeExtensionName}", SearchOption.AllDirectories);
                foreach (var filePath in files)
                {
                    var theme = Deserialize(filePath);
                    if (theme != null)
                    {
                        theme.FilePath = filePath;
                        list.Add(theme);
                    }
                }
            }

            // the current theme may be custom and not in themes folders
            var current = ShellBatInstance.Current.Theme;
            if (!list.Any(t => t.FilePath.EqualsIgnoreCase(current.FilePath)))
            {
                list.Add(current);
            }

            var names = list.Select(t => IOUtilities.PathRemoveExtension(t.FilePath, FileExtension.ShellBatThemeExtensionName)).WhereNotNull().Shorten();
            for (var i = 0; i < list.Count; i++)
            {
                list[i].DisplayName = names[i];
            }

            return list.AsReadOnly();
        }
    }

    // determine possible theme paths ordered by priority
    private static IEnumerable<string> GetThemePaths()
    {
        yield return Settings.ThemesPath;
        if (Environment.ProcessPath != null)
        {
            yield return Environment.ProcessPath;
            yield return Path.Combine(Environment.ProcessPath, ThemesDirectoryName);
        }
    }

    internal static ShellBatTheme LoadTheme(string? firstArg)
    {
        // passed as argument?
        var themeFilePath = CommandLine.Current.GetNullifiedArgument(Program.ThemeArgumentName);
        ShellBatTheme? theme;
        if (themeFilePath != null)
        {
            theme = Deserialize(themeFilePath);
            if (theme != null)
            {
                theme.FilePath = themeFilePath;
                return theme;
            }
        }

        // double-clicked on a theme file?
        if (firstArg != null && Path.GetExtension(firstArg).EqualsIgnoreCase(FileExtension.ShellBatThemeExtensionName))
        {
            CommandLine.Current.PositionedArguments.Remove(0);
            theme = Deserialize(firstArg);
            if (theme != null)
            {
                theme.FilePath = firstArg;
                return theme;
            }
        }

        // in instance settings?
        var path = ShellBatInstance.Current.Settings.ThemeFilePath;
        if (path != null)
        {
            if (!Path.IsPathRooted(path))
            {
                foreach (var themePath in GetThemePaths())
                {
                    var combinedPath = Path.Combine(themePath, path);
                    if (!IOUtilities.PathIsFile(combinedPath))
                    {
                        if (!Path.GetExtension(path).EqualsIgnoreCase(FileExtension.ShellBatThemeExtensionName))
                        {
                            combinedPath = Path.Combine(themePath, path + FileExtension.ShellBatThemeExtensionName);
                            if (!IOUtilities.PathIsFile(combinedPath))
                                continue;
                        }
                    }

                    theme = Deserialize(combinedPath);
                    if (theme != null)
                    {
                        theme.FilePath = combinedPath;
                        return theme;
                    }
                }
            }

            theme = Deserialize(path);
            if (theme != null)
            {
                theme.FilePath = path;
                return theme;
            }
        }

        return new();
    }
}
